# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fin_year', models.DateTimeField()),
                ('account_type', models.TextField()),
                ('label', models.TextField()),
                ('mun_name', models.TextField()),
                ('mun_code', models.CharField(max_length=5)),
                ('province', models.TextField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
            ],
        ),
    ]
