# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancesheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mun_code', models.CharField(max_length=5)),
                ('efficient_measure', models.DecimalField(decimal_places=5, max_digits=12)),
                ('wellfare_measure', models.DecimalField(decimal_places=5, max_digits=12)),
                ('fin_date', models.DateTimeField()),
                ('province', models.TextField()),
                ('profile', models.IntegerField()),
            ],
        ),
    ]
